name: Traffic to Coffee-Cluster

on: 
  schedule:
    # Runs every 12 hours;
    - cron: '0 */12 * * *' 
  push:
    branches:
      - main
    
jobs:
  visit-url:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Visit URL
        run: |
          curl -sSf https://coffee-cluster.streamlit.app/ || echo "Failed to access coffee-cluster.streamlit.app"
        timeout-minutes: 5
